<?php
/**
 * Copyright (c) 2017. sn
 */

namespace backend\models;

use backend\behaviors\VerifyPermissionBehavior;
use backend\models\traits\ExtendHistoryFindConditionTrait;
use common\models\RecoverableActiveRecord;
use yii\db\ActiveRecord;

/**
 * This is the model class for table "history".
 *
 * @property integer $id
 * @property string $name
 * @property integer $parent
 * @property integer $company_id
 * @property string $type
 * @property integer $created_at
 * @property integer $created_by
 */
class History extends \common\models\History
{
    use ExtendHistoryFindConditionTrait;

    public function delete()
    {
        $this->off(ActiveRecord::EVENT_BEFORE_DELETE);
        $this->off(ActiveRecord::EVENT_AFTER_DELETE);
        return parent::delete(); // TODO: Change the autogenerated stub
    }


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['VerifyPermissionBehavior'] = [
            'class' => VerifyPermissionBehavior::className()
        ];

        return $behaviors;
    }

}
