<?php


namespace backend\widgets;

use yii\helpers\Url;

/**
 * Class ActiveForm
 * @package backend\widgets
 */
class ActiveForm extends \yii\widgets\ActiveForm
{
    public $fieldClass = ActiveField::class;

    public function run()
    {
        $this->action = Url::to($this->action, true);
        parent::run(); // TODO: Change the autogenerated stub
    }


}